FROM nginx:1.28.0-alpine3.21@sha256:30f1c0d78e0ad60901648be663a710bdadf19e4c10ac6782c235200619158284

RUN apk add --no-cache openssl=3.3.7-r0

COPY --chown=101:101 nginx/nginx.conf /etc/nginx/nginx.conf
COPY --chown=101:101 nginx/proxy-entrypoint.sh /usr/local/bin/proxy-entrypoint.sh

RUN chmod 0555 /usr/local/bin/proxy-entrypoint.sh

USER 101:101

ENTRYPOINT ["/usr/local/bin/proxy-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
