CREATE TABLE assessments (
    assessment_id TEXT PRIMARY KEY,
    test_code TEXT NOT NULL,
    test_version TEXT NOT NULL,
    project TEXT NOT NULL,
    participant_id TEXT NOT NULL,
    participant_name TEXT NOT NULL,
    initials TEXT,
    visit TEXT NOT NULL,
    evaluator TEXT NOT NULL,
    assessment_date TEXT NOT NULL,
    started_at TEXT NOT NULL,
    source_file TEXT NOT NULL,
    imported_at TEXT NOT NULL,
    import_status TEXT NOT NULL
);

CREATE TABLE assessment_metrics (
    metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id TEXT NOT NULL,
    metric_code TEXT NOT NULL,
    metric_label TEXT NOT NULL,
    metric_value DOUBLE PRECISION NOT NULL,
    unit TEXT,
    calculated_at TEXT NOT NULL,
    CONSTRAINT fk_assessment_metrics_assessment
        FOREIGN KEY (assessment_id)
        REFERENCES assessments(assessment_id)
        ON DELETE CASCADE
);

CREATE TABLE trial_results (
    trial_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id TEXT NOT NULL,
    block TEXT NOT NULL CHECK (block IN ('practice', 'main')),
    trial_number INTEGER NOT NULL CHECK (trial_number > 0),
    word TEXT NOT NULL,
    ink_color TEXT NOT NULL,
    condition TEXT NOT NULL CHECK (condition IN ('congruent', 'incongruent')),
    correct_response TEXT CHECK (correct_response IS NULL OR correct_response = 'space'),
    key_pressed TEXT CHECK (key_pressed IS NULL OR key_pressed = 'space'),
    reaction_time DOUBLE PRECISION CHECK (reaction_time IS NULL OR reaction_time > 0),
    correct INTEGER NOT NULL CHECK (correct IN (0, 1)),
    error_type TEXT NOT NULL CHECK (
        error_type IN ('hit', 'omission', 'correct_rejection', 'commission')
    ),
    CONSTRAINT fk_trial_results_assessment
        FOREIGN KEY (assessment_id)
        REFERENCES assessments(assessment_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_assessments_participant_id ON assessments(participant_id);
CREATE INDEX idx_assessments_project ON assessments(project);
CREATE INDEX idx_assessments_assessment_date ON assessments(assessment_date);
CREATE INDEX idx_assessments_visit ON assessments(visit);
CREATE INDEX idx_assessments_evaluator ON assessments(evaluator);
CREATE INDEX idx_assessment_metrics_assessment_metric
    ON assessment_metrics(assessment_id, metric_code);
CREATE INDEX idx_trial_results_assessment_block
    ON trial_results(assessment_id, block);
