CREATE TABLE app_users (
    issuer TEXT NOT NULL CHECK (
        issuer IN ('https://accounts.google.com', 'accounts.google.com')
    ),
    subject TEXT NOT NULL CHECK (
        char_length(subject) BETWEEN 1 AND 255
    ),
    email TEXT CHECK (
        email IS NULL OR char_length(email) BETWEEN 3 AND 320
    ),
    role TEXT NOT NULL CHECK (
        role IN ('consulta', 'importacao', 'administracao')
    ),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_issuer TEXT,
    created_by_subject TEXT,
    PRIMARY KEY (issuer, subject),
    CONSTRAINT app_users_creator_complete CHECK (
        (created_by_issuer IS NULL) = (created_by_subject IS NULL)
    )
);

CREATE TABLE auth_audit_events (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    issuer TEXT,
    subject TEXT,
    action TEXT NOT NULL CHECK (
        action IN (
            'view_dashboard',
            'export_dashboard',
            'import_csv',
            'manage_users',
            'bootstrap_admin',
            'recover_admin'
        )
    ),
    outcome TEXT NOT NULL CHECK (
        outcome IN (
            'allowed',
            'success',
            'rejected',
            'failure',
            'denied_unregistered',
            'denied_blocked',
            'denied_expired',
            'denied_forbidden',
            'rate_limited'
        )
    ),
    request_id UUID NOT NULL,
    CONSTRAINT auth_audit_identity_complete CHECK (
        (issuer IS NULL) = (subject IS NULL)
    )
);

CREATE INDEX idx_app_users_role_active ON app_users(role, active);
CREATE INDEX idx_auth_audit_identity_time
    ON auth_audit_events(issuer, subject, occurred_at DESC);
CREATE INDEX idx_auth_audit_action_time
    ON auth_audit_events(action, occurred_at DESC);
