CREATE TABLE import_audit_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    request_id UUID NOT NULL UNIQUE,
    content_sha256 CHAR(64) NOT NULL CHECK (
        content_sha256 ~ '^[0-9a-f]{64}$'
    ),
    status TEXT NOT NULL CHECK (
        status IN ('importado', 'rejeitado')
    ),
    error_code TEXT CHECK (
        error_code IS NULL OR error_code IN (
            'invalid_envelope',
            'duplicate_assessment',
            'validation_or_service_failure'
        )
    ),
    CONSTRAINT import_audit_error_consistent CHECK (
        (status = 'importado' AND error_code IS NULL)
        OR (status = 'rejeitado' AND error_code IS NOT NULL)
    )
);

CREATE INDEX idx_import_audit_occurred_at
    ON import_audit_events(occurred_at DESC);
